version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres15-cshub
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cshub-local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - cshub

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-cshub
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - cshub

  api:
    image: cshub-api:latest
    build: .
    container_name: cshub-api
    ports:
      - '4000:4000'
    env_file:
      - '.env.development'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - cshub

networks:
  cshub:
    external: true

volumes:
  postgres_data:
